name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "seraphus1/test"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ vars.DOCKER_USER }}/docker-build-cloud-demo:latest
          push: ${{ github.event_name != 'pull_request' }}
  
